# Generated by Django 4.2 on 2023-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_site', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='settings/logo/')),
                ('banner_one', models.ImageField(upload_to='settings/banner/')),
                ('banner_two', models.ImageField(upload_to='settings/banner/')),
            ],
        ),
    ]
