# Generated by Django 4.2 on 2023-05-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingshomepage',
            name='logo',
        ),
    ]
