# Generated by Django 4.2 on 2023-05-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_settingshomepage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingshomepage',
            name='banner_one_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingshomepage',
            name='banner_one_title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingshomepage',
            name='banner_two_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingshomepage',
            name='banner_two_title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
