# Generated by Django 4.2 on 2023-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalspecialization',
            options={'verbose_name_plural': 'Дополнительная специалиция'},
        ),
        migrations.AlterModelOptions(
            name='mainspecialization',
            options={'verbose_name_plural': 'Основная Специализации'},
        ),
        migrations.AlterModelOptions(
            name='psychologist',
            options={'verbose_name_plural': 'Психологи'},
        ),
        migrations.AlterModelOptions(
            name='psychologiststatus',
            options={'verbose_name_plural': 'Статус Психологи'},
        ),
        migrations.AddField(
            model_name='psychologist',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
