# Generated by Django 4.2 on 2023-04-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0004_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateField()),
                ('to_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologist.psychologist')),
            ],
            options={
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
