# Generated by Django 4.2 on 2023-04-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_psylo', to='psychologist.psychologist'),
        ),
    ]
