# Generated by Django 4.2 on 2023-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0008_alter_psychologist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='additional_specialization_one',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='main_specialization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
