# Generated by Django 4.2 on 2023-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0009_alter_psychologist_additional_specialization_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='online_consultation',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='personal_reception',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7),
        ),
    ]
