# Generated by Django 4.2 on 2023-04-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0011_psychologist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
