# Generated by Django 4.2 on 2023-05-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0012_alter_psychologist_bio_alter_psychologist_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_whom',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
