# Generated by Django 4.2 on 2023-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0013_remove_comment_to_whom_delete_blog_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='image',
            field=models.FileField(upload_to='psychologist'),
        ),
    ]
