# Generated by Django 4.2 on 2023-05-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0014_alter_psychologist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='psychologist'),
        ),
    ]
